apiVersion: apps/v1
kind: Deployment
metadata:
     name: deploy-nginx
     labels:
       app: nginx-app
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-container
        image: prithiviraj123/nginx-img2
        ports:
        - containerPort: 80
